apiVersion: apps/v1
kind: Deployment
metadata:
  name: influxdb-grafana-mqtt
spec:
  replicas: 1
  selector:
    matchLabels:
      app: influxdb-grafana-mqtt
  template:
    metadata:
      labels:
        app: influxdb-grafana-mqtt
    spec:
      containers:
        - name: influxdb
          image: influxdb
          ports:
            - containerPort: 8086
          env:
          - name: INFLUXDB_HOST
            value: "influxdb"
          - name: INFLUXDB_HTTP_AUTH_ENABLED
            value: "false"
        #- name: grafana
        #  image: grafana/grafana
        #  ports:
        #    - containerPort: 3000
        #  env:
        #  - name: GF_INSTALL_PLUGINS
        #    value: "grafana-clock-panel,grafana-simple-json-datasource"
        #  - name: GF_AUTH_ANONYMOUS_ENABLED
        #    value: "true"
        #  - name: GF_AUTH_ANONYMOUS_ORG_ROLE
        #    value: "Viewer"
        #  - name: GF_AUTH_BASIC_ENABLED
        #    value: "false"
        #  - name: GF_AUTH_DISABLE_LOGIN_FORM
        #    value: "true"
        #  - name: GF_AUTH_PROXY_ENABLED
        #    value: "false"
        #  - name: GF_AUTH_SIGNOUT_REDIRECT_URL
        #    value: "/"
        #  - name: GF_DATABASE_TYPE
        #    value: "influxdb"
        #  - name: GF_DATABASE_URL
        #    value: "http://influxdb:8086"
        #  - name: GF_DATABASE_NAME
        #    value: "mydb"
        #  - name: GF_AUTH_DISABLE_LOGIN
        #    value: "true"
          #- name: GF_DATABASE_USER
          #  value: "myuser"
          #- name: GF_DATABASE_PASSWORD
          #  value: "mypassword"

        - name: mqtt-broker
          image: eclipse-mosquitto
          ports:
            - containerPort: 1883
      volumes:
        - name: influxdb-data
          persistentVolumeClaim:
            claimName: influxdb-data-claim2
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: influxdb-data-claim2
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
---
apiVersion: v1
kind: Service
metadata:
  name: influxdb-grafana-mqtt-service
spec:
  selector:
    app: influxdb-grafana-mqtt
  type: NodePort
  ports:
    - name: influxdb
      port: 8086
      targetPort: 8086
      nodePort: 30001
    - name: grafana
      port: 3000
      targetPort: 3000
      nodePort: 30002
    - name: mqtt
      port: 1883
      targetPort: 1883
      nodePort: 30003